site_name: Sabre Documentation
theme:
  name: 'material'
nav:
  - Home: index.md
  - Getting started: getting-started/installation.md
  - Components:
      - 'Buttons': 'components/buttons.md'
google_analytics: ['UA-145439139-1', 'sabrecss.netlify.com']